import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os'; import { fileURLToPath } from 'node:url';
import { evaluateHandoff, runGate } from './handoff-quality-gate.mjs';
import { spawnSync } from 'node:child_process';
const catalog = JSON.parse(fs.readFileSync(new URL('./automation-routes.json', import.meta.url), 'utf8'));
const gatePath = fileURLToPath(new URL('./handoff-quality-gate.mjs', import.meta.url));
const handoff = '以下の手順を実行してください\n1. スクリプトを開いてください\n2. ファイルを選択してください\n3. ▶実行してください\n4. OAuthに同意してください\n5. 完了を報告してください';
const cli = (text, { enforcement, executable = gatePath } = {}) => {
  const h=fs.mkdtempSync(path.join(os.tmpdir(),'hqg-cli-'));
  if(enforcement){fs.mkdirSync(path.join(h,'.claude'));fs.writeFileSync(path.join(h,'.claude','rule-enforcement.json'),JSON.stringify(enforcement));}
  return spawnSync(process.execPath,[executable],{input:JSON.stringify({session_id:'cli-regression',assistant_text:text}),encoding:'utf8',env:{...process.env,ORGIAST_HOME:h}});
};
test('1 旧gateをすり抜けた実物をblock', () => assert.equal(evaluateHandoff('`clasp run-function` は NOT_FOUND で不可（Workspaceポリシー制約）\n' + handoff, { catalog }).decision, 'block'));
test('2 正当な品質手渡しをpass', () => assert.equal(evaluateHandoff(handoff+'\n**[手渡し判定]**\n- 品質理由: 受注ステータスは経営判断のため\n- 試した自動化経路: Sheets API は権限なし・DWD は未設定・impersonate は対象外・clasp run-function は失敗\n- 未試行で却下した経路: Drive API は更新対象外', { catalog }).decision, 'pass'));
test('3 効率理由をblock', () => assert.equal(evaluateHandoff(handoff+'\n[手渡し判定]\n品質理由: 実装が面倒なので\n試した自動化経路: Sheets API, DWD, impersonate\n未試行で却下した経路: Drive API は対象外', { catalog }).decision, 'block'));
test('4 廃止タグをblock', () => assert.equal(evaluateHandoff(handoff+'\n[HANDOFF-OK]', { catalog }).decision, 'block'));
test('4a 手渡しゼロで廃止タグへの言及はpass', () => assert.equal(evaluateHandoff('このタグは廃止した: [HANDOFF-OK]', { catalog }).decision, 'pass'));
test('4b 手渡しありでバックティック内の廃止タグへの言及はpass', () => assert.equal(evaluateHandoff(handoff+'\n`[HANDOFF-OK]` は旧形式です。\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD, impersonate\n未試行で却下した経路: Drive API は対象外', { catalog }).decision, 'pass'));
test('4c 手渡しありで廃止タグの素の使用はblock', () => assert.equal(evaluateHandoff(handoff+'\n[HANDOFF-OK]\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD, impersonate\n未試行で却下した経路: Drive API は対象外', { catalog }).decision, 'block'));
test('4d 手渡しありでコードブロック内の廃止タグへの言及はpass', () => assert.equal(evaluateHandoff(handoff+'\n```text\n[HANDOFF-OK]\n```\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD, impersonate\n未試行で却下した経路: Drive API は対象外', { catalog }).decision, 'pass'));
test('5 経路2件をblock', () => assert.equal(evaluateHandoff(handoff+'\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD\n未試行で却下した経路: Drive API は対象外', { catalog }).decision, 'block'));
test('7 過去形の完了報告はpass', () => assert.equal(evaluateHandoff('1. WSL2を導入した\n2. Nodeを設定した\n3. テストを実行した', { catalog }).decision, 'pass'));
test('10 enforcement=block は経路4件・却下2件ならpass', () => { const h=fs.mkdtempSync(path.join(os.tmpdir(),'hqg-')); fs.mkdirSync(path.join(h,'.claude')); fs.writeFileSync(path.join(h,'.claude','rule-enforcement.json'),JSON.stringify({'handoff-quality-only':{mode:'block',forceAll:true,reason:'test'}})); const old=process.env.ORGIAST_HOME; process.env.ORGIAST_HOME=h; try { const r=runGate({assistant_text:handoff+'\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD, impersonate, clasp run-function\n未試行で却下した経路: Drive API, Apps Script API'}); assert.equal(r.decision,'pass'); } finally { old===undefined?delete process.env.ORGIAST_HOME:process.env.ORGIAST_HOME=old; } });
test('10b enforcement=block は従来水準の経路3件・却下1件をblock', () => assert.equal(evaluateHandoff(handoff+'\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD, impersonate\n未試行で却下した経路: Drive API', { catalog, enforcement:{'handoff-quality-only':{mode:'block'}} }).decision, 'block'));
test('11 ledger excerptが非空',()=>{const h=fs.mkdtempSync(path.join(os.tmpdir(),'hqg-ledger-'));const input={session_id:'excerpt-test',assistant_text:handoff+'\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD, impersonate\n未試行で却下した経路: Drive API'};const p=spawnSync(process.execPath,[gatePath],{input:JSON.stringify(input),encoding:'utf8',env:{...process.env,ORGIAST_HOME:h}});assert.equal(p.status,0,p.stderr);const record=JSON.parse(fs.readFileSync(path.join(h,'.claude','handoff-ledger.jsonl'),'utf8'));assert.ok(record.excerpt.length>0);assert.match(record.excerpt,/以下の手順/);});
test('12 excerptが空なら警告してledgerを書かない',()=>{const h=fs.mkdtempSync(path.join(os.tmpdir(),'hqg-empty-'));const p=spawnSync(process.execPath,[gatePath],{input:JSON.stringify({session_id:'empty',stop_hook_active:true}),encoding:'utf8',env:{...process.env,ORGIAST_HOME:h}});assert.equal(p.status,0);assert.match(p.stderr,/excerpt が空/);assert.equal(fs.existsSync(path.join(h,'.claude','handoff-ledger.jsonl')),false);});
test('13 ledger書き込み失敗を警告してblock判定を維持',()=>{const h=fs.mkdtempSync(path.join(os.tmpdir(),'hqg-unwritable-'));fs.writeFileSync(path.join(h,'.claude'),'directory blocker');const input={session_id:'write-failure',assistant_text:handoff};const p=spawnSync(process.execPath,[gatePath],{input:JSON.stringify(input),encoding:'utf8',env:{...process.env,ORGIAST_HOME:h}});assert.equal(p.status,0,p.stderr);assert.match(p.stderr,/\[handoff-quality-gate\] ledger書き込み失敗: .+ path=/);assert.deepEqual(JSON.parse(p.stdout),{decision:'block',reason:'`[手渡し判定]` ブロックがありません。'});});
test('14 CLI起動で経路2件のblock JSONをstdoutへ返す',()=>{const p=cli(handoff+'\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD\n未試行で却下した経路: Drive API');assert.equal(p.status,0,p.stderr);assert.equal(JSON.parse(p.stdout).decision,'block');});
test('15 enforcement=block のCLIで経路3件をblock',()=>{const p=cli(handoff+'\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD, impersonate\n未試行で却下した経路: Drive API, Apps Script API',{enforcement:{'handoff-quality-only':{mode:'block'}}});assert.equal(p.status,0,p.stderr);assert.equal(JSON.parse(p.stdout).decision,'block');assert.match(JSON.parse(p.stdout).reason,/3件.*4件以上/);});
test('16 enforcement=block のCLIで経路4件・却下2件をpass',()=>{const p=cli(handoff+'\n[手渡し判定]\n品質理由: 経営判断のため\n試した自動化経路: Sheets API, DWD, impersonate, clasp run-function\n未試行で却下した経路: Drive API, Apps Script API',{enforcement:{'handoff-quality-only':{mode:'block'}}});assert.equal(p.status,0,p.stderr);assert.equal(p.stdout,'');});
const junctionGate=path.join(os.homedir(),'orgiast-claude-rules','tools','handoff-quality-gate.mjs');
let junctionAvailable=false;try{junctionAvailable=fs.existsSync(junctionGate)&&fs.realpathSync(junctionGate)===fs.realpathSync(gatePath);}catch{}
test('17 ジャンクション経路でもCLIが起動する（ジャンクションなしは明示skip）',{skip:!junctionAvailable},()=>{const p=cli(handoff,{executable:junctionGate});assert.equal(p.status,0,p.stderr);assert.equal(JSON.parse(p.stdout).decision,'block');});
test('18 JSON入力を解釈後に手渡し判定を省略した場合はstderrへ理由を出す',()=>{const p=cli('通常の説明だけです');assert.equal(p.status,0);assert.equal(p.stdout,'');assert.match(p.stderr,/判定をスキップしました: 手渡しなし/);});
test('19 不正JSONは警告しスキップを1行記録する',()=>{const h=fs.mkdtempSync(path.join(os.tmpdir(),'hqg-bad-json-'));const raw='{"session_id":"bad","assistant_text":"line1\nline2"}';const p=spawnSync(process.execPath,[gatePath],{input:raw,encoding:'utf8',env:{...process.env,ORGIAST_HOME:h}});assert.equal(p.status,0);assert.equal(p.stdout,'');assert.match(p.stderr,/JSONとして解釈できず/);const records=fs.readFileSync(path.join(h,'.claude','handoff-gate-skips.jsonl'),'utf8').trim().split(/\r?\n/);assert.equal(records.length,1);assert.equal(JSON.parse(records[0]).rawHead,raw.slice(0,120));});
test('20 空stdinは警告するがスキップを記録しない',()=>{const h=fs.mkdtempSync(path.join(os.tmpdir(),'hqg-empty-stdin-'));const p=spawnSync(process.execPath,[gatePath],{input:'',encoding:'utf8',env:{...process.env,ORGIAST_HOME:h}});assert.equal(p.status,0);assert.equal(p.stdout,'');assert.match(p.stderr,/入力が空/);assert.equal(fs.existsSync(path.join(h,'.claude','handoff-gate-skips.jsonl')),false);});
test('21 本文なしは警告しスキップを記録する',()=>{const h=fs.mkdtempSync(path.join(os.tmpdir(),'hqg-no-body-'));const p=spawnSync(process.execPath,[gatePath],{input:JSON.stringify({session_id:'x'}),encoding:'utf8',env:{...process.env,ORGIAST_HOME:h}});assert.equal(p.status,0);assert.equal(p.stdout,'');assert.match(p.stderr,/本文が取得できませんでした/);const record=JSON.parse(fs.readFileSync(path.join(h,'.claude','handoff-gate-skips.jsonl'),'utf8'));assert.equal(record.sessionId,'x');});
test('22 正常block入力はstderrに警告を出さない',()=>{const p=cli(handoff);assert.equal(p.status,0);assert.equal(p.stderr,'');assert.equal(JSON.parse(p.stdout).decision,'block');});
